### ISSUE TITLE
rocky linux 8 + php 8.0 + nginx 1.23.1

### ISSUE THREAD

**Issue by stanley87** [rryqszq4/ngx-php#145]
Hi @rryqszq4 , my side was follow your instruction try to install for php 8.0 + nginx 1.23.1

However i am stuck at this place

yum install nginx-module-php7 (your existing instruction)

yum install nginx-module-php8 (i am stuck here, this repo not exist, how can i manual to fix this myself / build myself to continue remaining installation part as below ? )

Edit nginx.conf and load the required modules at the top:

load_module modules/ndk_http_module.so;
load_module modules/ngx_http_php_module.so;

**Comment by stanley87** [comment]
anyone can assist my issue also welcome, tq in advance

**Comment by stanley87** [comment]
problem solved

**Comment by ShuiPingYang** [comment]
@stanley87 bro,how to solve this problem ? I document said it only suitable for  nginx-1.4.7 ~ nginx-1.19.5 ,and my nginx version  is 1.20.0
